2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Configure stats pid to 69408
2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Loading settings from C:\Users\giaco\.config\wandb\settings
2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Loading settings from C:\Users\giaco\Documents\QPNN\QPNN\wandb\settings
2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'entity': 'quantum_kets', 'project': 'QPNN_TRAIN_SWEEP_iris', 'root_dir': 'C:\\Users\\giaco\\Documents\\QPNN\\QPNN', 'run_id': 'b35cv7e8', 'sweep_param_path': 'C:\\Users\\giaco\\Documents\\QPNN\\QPNN\\wandb\\sweep-tpf9qg89\\config-b35cv7e8.yaml', 'sweep_id': 'tpf9qg89'}
2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-07 17:48:40,750 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:_log_setup():533] Logging user logs to C:\Users\giaco\Documents\QPNN\QPNN\wandb\run-20241107_174840-b35cv7e8\logs\debug.log
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:_log_setup():534] Logging internal logs to C:\Users\giaco\Documents\QPNN\QPNN\wandb\run-20241107_174840-b35cv7e8\logs\debug-internal.log
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:_jupyter_setup():479] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002361285DBD0>
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():619] calling init triggers
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():626] wandb.init called with sweep_config: {'arch_elements': 4, 'batch_size': 84, 'epochs': 100, 'learning_rate': 0.009842310429000174, 'optimizer': 'ADAMW'}
config: {}
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():669] starting backend
2024-11-07 17:48:40,751 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():673] sending inform_init request
2024-11-07 17:48:40,765 INFO    Thread-21 (_run_job):69408 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-07 17:48:40,767 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():686] backend started and connected
2024-11-07 17:48:40,788 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_config_callback():1389] config_cb None None {'arch_elements': 4, 'batch_size': 84, 'epochs': 100, 'learning_rate': 0.009842310429000174, 'optimizer': 'ADAMW'}
2024-11-07 17:48:40,789 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_label_probe_notebook():1341] probe notebook
2024-11-07 17:48:40,789 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_label_probe_notebook():1351] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-11-07 17:48:40,789 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():781] updated telemetry
2024-11-07 17:48:40,846 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-07 17:48:41,214 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():867] starting run threads in backend
2024-11-07 17:48:41,699 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_console_start():2451] atexit reg
2024-11-07 17:48:41,699 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_redirect():2299] redirect: wrap_raw
2024-11-07 17:48:41,699 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_redirect():2364] Wrapping output streams.
2024-11-07 17:48:41,699 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_redirect():2389] Redirects installed.
2024-11-07 17:48:41,700 INFO    Thread-21 (_run_job):69408 [wandb_init.py:init():911] run started, returning control to user process
2024-11-07 17:49:18,922 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_finish():2146] finishing run quantum_kets/QPNN_TRAIN_SWEEP_iris/b35cv7e8
2024-11-07 17:49:18,923 INFO    Thread-21 (_run_job):69408 [jupyter.py:save_history():459] not saving jupyter history
2024-11-07 17:49:18,923 INFO    Thread-21 (_run_job):69408 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2024-11-07 17:49:18,923 INFO    Thread-21 (_run_job):69408 [wandb_init.py:_jupyter_teardown():461] cleaning up jupyter logic
2024-11-07 17:49:18,923 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_atexit_cleanup():2414] got exitcode: 0
2024-11-07 17:49:18,923 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_restore():2396] restore
2024-11-07 17:49:18,923 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_restore():2402] restore done
2024-11-07 17:49:22,781 WARNING MsgRouterThr:69408 [router.py:message_loop():75] message_loop has been closed
2024-11-07 17:49:22,968 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_restore():2396] restore
2024-11-07 17:49:22,968 INFO    Thread-21 (_run_job):69408 [wandb_run.py:_restore():2402] restore done
2024-11-07 17:49:22,968 ERROR   Thread-21 (_run_job):69408 [wandb_run.py:_atexit_cleanup():2435] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\wandb_run.py", line 2426, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\wandb_run.py", line 2676, in _on_finish
    _ = exit_handle.wait(
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\lib\mailbox.py", line 294, in wait
    on_probe(probe_handle)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\wandb_run.py", line 2640, in _on_probe_exit
    handle = self._backend.interface.deliver_poll_exit()
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\interface\interface.py", line 950, in deliver_poll_exit
    return self._deliver_poll_exit(poll_exit)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 483, in _deliver_poll_exit
    return self._deliver_record(record)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 452, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\lib\mailbox.py", line 451, in _deliver_record
    interface._publish(record)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\lib\sock_client.py", line 225, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\lib\sock_client.py", line 157, in send_server_request
    self._send_message(msg)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\giaco\anaconda3\envs\pennylane3.10\lib\site-packages\wandb\sdk\lib\sock_client.py", line 132, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto
